name: Build AggilRemote Pro Custom

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout Código (Recursive)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Personalizar Branding e Configurações
        shell: bash
        run: |
          # 1. Identidade e Servidor (Usando aspas simples para evitar erros de shell)
          sed -i 's/RustDesk/AggilRemote/g' libs/hbb_common/src/config.rs
          sed -i 's/Purslane Ltd/DJ Info PE Tecnologia/g' libs/hbb_common/src/config.rs
          sed -i "s/rs-ny.rustdesk.com/remote.djinfope.com.br/g" libs/hbb_common/src/config.rs
          sed -i "s|OeVuKk5nlHiXp+APNn0Y3pC1Iwpwn44JGqrQCsWqmBw=|${{ secrets.MY_KEY }}|g" libs/hbb_common/src/config.rs
          
          # 2. Links
          sed -i 's|https://rustdesk.com|https://www.djinfope.com.br|g' libs/hbb_common/src/config.rs
          
          # 3. Interface e Permissões (Ativando o que você pediu)
          sed -i 's/direct_ip_access = false/direct_ip_access = true/g' libs/hbb_common/src/config.rs
          sed -i 's/display_offline_addressbook = false/display_offline_addressbook = true/g' libs/hbb_common/src/config.rs
          
          # 4. Comportamento (Instalação e Wallpaper)
          sed -i 's/remove_wallpaper = false/remove_wallpaper = true/g' libs/hbb_common/src/config.rs
          sed -i 's/const DISABLE_INSTALL: bool = true/const DISABLE_INSTALL: bool = false/g' libs/hbb_common/src/config.rs

          # 5. Aplicar Imagens
          cp branding/icon.ico res/icon.ico
          cp branding/icon.ico res/tray-icon.ico
          cp branding/logo.png res/logo.png
          cp branding/privacy.png res/privacy.png

      - name: Instalar Dependências
        run: |
          vcpkg install --triplet x64-windows-static --vcpkg-root "C:\vcpkg" --classic libvpx libyuv opus aom dav1d

      - name: Compilar Executável
        shell: pwsh
        run: |
          $env:VCPKG_ROOT = "C:\vcpkg"
          cargo build --release
          # Renomeia o executável para o seu nome personalizado
          Rename-Item -Path "target/release/rustdesk.exe" -NewName "AggilRemote.exe"

      - name: Gerar Artefato para Download
        uses: actions/upload-artifact@v4
        with:
          name: AggilRemote-Windows-Final
          path: target/release/AggilRemote.exe
